package exchangesys.frame;

import exchange.db.DBArea;
import exchange.db.DBConnect;
import exchange.db.DBUser;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Exception.MyException;
import utils.DoubleUtils;
import utils.StringUtils;

/**
 *
 * @author myy
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        try {
            initComponents();
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            init();
        } catch (Exception ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex + "\n" + ex.getMessage());
        }
    }

    private void init() throws Exception {
        Connection conn = DBConnect.getConnection();
        DBArea.showProvInCB(conn, cb_prov);
        DBConnect.closeDB(conn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_prov = new javax.swing.JComboBox();
        cb_city = new javax.swing.JComboBox();
        cb_area = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_acount = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        tf_tel = new javax.swing.JTextField();
        pf_pw = new javax.swing.JPasswordField();
        pf_repw = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        but_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("易物宝注册");
        setResizable(false);

        jLabel1.setText("账户：");

        jLabel2.setText("密码：");

        jLabel3.setText("昵称：");

        jLabel4.setText("确认密码：");

        jLabel5.setText("地址：");

        cb_prov.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_provItemStateChanged(evt);
            }
        });

        cb_city.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_cityItemStateChanged(evt);
            }
        });

        jLabel6.setText("省");

        jLabel7.setText("市");

        jLabel8.setText("区");

        jLabel10.setText("电话:");

        jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        jLabel12.setText("注册账户");

        but_register.setText("注册");
        but_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_acount, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_name, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pf_pw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                    .addComponent(pf_repw, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_prov, 0, 124, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but_register)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_city, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cb_area, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_acount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pf_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pf_repw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cb_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cb_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(but_register)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_provItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_provItemStateChanged
        try {
            Connection conn = DBConnect.getConnection();
            String prov = cb_prov.getSelectedItem().toString();
            int id = DBArea.getProvIdByName(conn, prov);
            if(id!=-1)
            {
                DBArea.showCityInCB(conn, cb_city, id);
            }
            DBConnect.closeDB(conn);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MyException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_cb_provItemStateChanged

    private void cb_cityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_cityItemStateChanged
       try {
            Connection conn = DBConnect.getConnection();
            if(cb_city.getSelectedItem()==null)
            {
                return;
            }
            String prov_name = cb_prov.getSelectedItem().toString();
            String city_name = cb_city.getSelectedItem().toString();
            int id = DBArea.getCityIdByName(conn,prov_name,city_name);
            if(id!=-1)
            {
                DBArea.showAreaInCB(conn, cb_area, id);
            }
            DBConnect.closeDB(conn);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MyException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_cb_cityItemStateChanged

    private void but_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_registerActionPerformed
        String acount = tf_acount.getText();
        String name = tf_name.getText();
        String password = pf_pw.getText();
        String repassword = pf_repw.getText();
        String tel =tf_tel.getText();
        if(StringUtils.isEmptyOrNull(acount)||StringUtils.isEmptyOrNull(name)||StringUtils.isEmptyOrNull(password)||
                StringUtils.isEmptyOrNull(repassword)||StringUtils.isEmptyOrNull(tel))
        {
             JOptionPane.showMessageDialog(this,"请完善各项信息！");
             return ;
        }
        if(password.equals(repassword)==false)
        {
            JOptionPane.showMessageDialog(this,"确认密码与密码不一致！");
             return ;
        }
        if(StringUtils.isTel(tel)==false)
        {
            JOptionPane.showMessageDialog(this,"号码格式不对！");
             return ;
        }
        
//        此处应有重复用户名查询
        try {
            Connection conn = DBConnect.getConnection();
            if(DBUser.hasResgiter(conn, acount)==true)
            {
                 JOptionPane.showMessageDialog(this,"用户名重复！");
                 return;
            }
            if(DBUser.nameHasResgiter(conn, name)==true)
            {
                JOptionPane.showMessageDialog(this,"昵称重复！");
                 return;
            }
            String prov_name = cb_prov.getSelectedItem().toString();
            String city_name = cb_city.getSelectedItem().toString();
            String area_name = cb_area.getSelectedItem().toString();
            int area_id = DBArea.getAreaIdByName(conn,prov_name,city_name,area_name);
            //添加用户
            DBUser.addUser(conn, name, acount, password, area_id, tel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex);
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        JOptionPane.showMessageDialog(this,"注册成功！");
        //关闭窗口
        this.dispose();
    }//GEN-LAST:event_but_registerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_register;
    private javax.swing.JComboBox cb_area;
    private javax.swing.JComboBox cb_city;
    private javax.swing.JComboBox cb_prov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField pf_pw;
    private javax.swing.JPasswordField pf_repw;
    private javax.swing.JTextField tf_acount;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_tel;
    // End of variables declaration//GEN-END:variables
}
