/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exchangesys.panel;

import exchange.db.DBConnect;
import exchange.db.DBForm;
import exchangesys.frame.ItemShowFrame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import Exception.MyException;

/**
 *
 * @author myy
 */
public class ItemPanel extends javax.swing.JPanel {

    public static final String DATE_FORMAT = "yyyy-MM-dd";
    public static int WIDTH=180,HEIGHT=250;
    private final Color DEFULT=new Color(187,255,255);
    private final Color HOVER=new Color(150,205,250);
    private final Color PRESS=new Color(125,180,250);
    private int form_id,user_id;
    
    public ItemPanel(int form_id,int user_id) {
        try {
            this.setBounds(0, 0, WIDTH, HEIGHT);
            this.user_id=user_id;
            this.form_id=form_id;
            initComponents();
            Connection conn=DBConnect.getConnection();
            //ÏÔÊ¾±íµ¥
            DBForm.showFormInPanel(conn, this, form_id);
            
            DBConnect.closeDB(conn);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MyException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_img = new javax.swing.JLabel();
        lab_title = new javax.swing.JLabel();
        lab_peo = new javax.swing.JLabel();
        lab_sub_man = new javax.swing.JLabel();
        lab_hot = new javax.swing.JLabel();

        setBackground(new java.awt.Color(187, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lab_img.setBackground(new java.awt.Color(153, 153, 153));
        lab_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_img.setPreferredSize(new java.awt.Dimension(120, 130));
        int par_w=this.getWidth();
        int par_h=this.getHeight();
        int h = (par_h/5)*4;
        //lab_img.setBounds(0, 0, par_w,par_h);
        lab_img.setBounds(0, 0, par_w,h);

        lab_title.setBackground(new java.awt.Color(102, 102, 102));
        lab_title.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18)); // NOI18N
        lab_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_title.setText("±êÌâ");
        lab_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lab_peo.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ Light", 0, 14)); // NOI18N
        lab_peo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_peo.setText("·¢²¼Ê±¼ä£º");

        lab_sub_man.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ Light", 0, 12)); // NOI18N
        lab_sub_man.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_sub_man.setText("·¢²¼ÈË:");

        lab_hot.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ Light", 0, 12)); // NOI18N
        lab_hot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_hot.setText("ÈÈ¶È:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(lab_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lab_peo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lab_sub_man, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lab_hot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lab_img, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lab_title)
                .addGap(2, 2, 2)
                .addComponent(lab_peo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_sub_man)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_hot, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        ItemShowFrame isf = new ItemShowFrame(form_id, user_id);
        isf.setVisible(true);
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(HOVER);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
       this.setBackground(DEFULT);
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       this.setBackground(PRESS);
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lab_hot;
    public javax.swing.JLabel lab_img;
    public javax.swing.JLabel lab_peo;
    public javax.swing.JLabel lab_sub_man;
    public javax.swing.JLabel lab_title;
    // End of variables declaration//GEN-END:variables
}
